version: '2.0'
services:
  gmail-cli:
    image: nnaydenovdocker/gmail-cli-tool:0.0.2
    volumes:
    - /root/Gmail_Tool:/root/Gmail_Tool
    - /root/mailbox:/root/mailbox
    restart: on-failure
    command: bash -c 'while true; do sleep 2; done'
